import { describe, expect, it } from "vitest";
import { exportBackup, exportCstimer, exportCsv, importAny, importCstimerTxt, solveKey } from "../cstimer";
import { migrateV1 } from "../migrate";
import { AppData, DEFAULT_SETTINGS } from "../types";

const CSTIMER_JSON = {
  session1: [
    [[0, 12345], "R U R' U'", "", 1700000000],
    [[2000, 10000], "F2 L2", "nice", 1700000100],
    [[-1, 9000], "B D", "", 1700000200],
  ],
  session2: [[[0, 30000, 20000, 15000, 5000], "R2 U2", "", 1700000300]],
  session3: [[[0, 3000], "R U F", "", 1700000400]],
  session4: [[[0, 11111], "L2 D", "", 1700000500]],
  properties: {
    sessionData: JSON.stringify({
      "1": { name: "Main", opt: {}, rank: 1 },
      "2": { name: "PLL practice", opt: { scrType: "pll" }, rank: 2 },
      "3": { name: 3, opt: { scrType: "222so" }, rank: 3 },
      "4": { name: "Second 3x3", opt: {}, rank: 4 },
    }),
    session: 1,
  },
};

const data = (solves: AppData["solves"]): AppData => ({ solves, settings: DEFAULT_SETTINGS, profile: "333" });

describe("cstimer json import", () => {
  it("sorts every session into its cube profile", () => {
    const r = importAny(JSON.stringify(CSTIMER_JSON));
    expect(r.format).toBe("cstimer-json");
    const by = (t: string) => r.solves.filter((s) => s.scrambleType === t);
    expect(by("333").map((s) => [s.time, s.penalty])).toEqual([
      [12345, 0],
      [10000, 2000],
      [9000, -1],
      [11111, 0],
    ]);
    expect(by("333-pll")[0]!.splits).toEqual([5000, 15000, 20000]);
    expect(by("222").map((s) => s.time)).toEqual([3000]);
    expect(by("333")[0]!.date).toBe(1700000000 * 1000);
  });

  it("round trips through the cstimer export", () => {
    const r = importAny(JSON.stringify(CSTIMER_JSON));
    const exported = JSON.parse(exportCstimer(data(r.solves)));
    const meta = JSON.parse(exported.properties.sessionData);
    const pllIdx = Object.keys(meta).find((k) => meta[k].opt.scrType === "pll")!;
    expect(exported[`session${pllIdx}`][0][0]).toEqual([0, 30000, 20000, 15000, 5000]);
    const again = importAny(JSON.stringify(exported));
    const key = (s: { time: number; penalty: number; scramble: string; scrambleType: string }) => `${s.scrambleType} ${s.time} ${s.penalty} ${s.scramble}`;
    expect(again.solves.map(key).sort()).toEqual(r.solves.map(key).sort());
  });

  it("gives identical solves the same dedupe key", () => {
    const a = importAny(JSON.stringify(CSTIMER_JSON)).solves.map(solveKey);
    const b = importAny(JSON.stringify(CSTIMER_JSON)).solves.map(solveKey);
    expect(a).toEqual(b);
    expect(new Set(a).size).toBe(a.length);
  });
});

describe("cstimer txt import", () => {
  it("parses a time list", () => {
    const txt = `Generated By csTimer on 2024-01-01
solves/total: 3/3

single
best: 10.00

Time List:
1. 12.34   R U R' U'   @2024-01-01 12:00:00
2. 14.00+   F2 L2   @2024-01-01 12:01:00
3. DNF(9.87)   B D   @2024-01-01 12:02:00`;
    const r = importCstimerTxt(txt);
    expect(r.solves.map((s) => [s.time, s.penalty, s.scramble])).toEqual([
      [12340, 0, "R U R' U'"],
      [12000, 2000, "F2 L2"],
      [9870, -1, "B D"],
    ]);
    expect(r.solves[0]!.date).toBe(Date.parse("2024-01-01T12:00:00"));
  });

  it("parses a plain list of times", () => {
    const r = importAny("12.34\n11.00\nDNF\n13.50+\n");
    expect(r.format).toBe("plain");
    expect(r.solves.map((s) => [s.time, s.penalty])).toEqual([
      [12340, 0],
      [11000, 0],
      [0, -1],
      [11500, 2000],
    ]);
  });
});

describe("kubetimr backups", () => {
  it("re imports a backup with fresh ids", () => {
    const r = importAny(JSON.stringify(CSTIMER_JSON));
    const back = importAny(exportBackup(data(r.solves)));
    expect(back.format).toBe("kubetimr");
    expect(back.solves).toHaveLength(r.solves.length);
    expect(back.solves[0]!.id).not.toBe(r.solves[0]!.id);
    expect(back.solves.map((s) => s.scrambleType)).toEqual(r.solves.map((s) => s.scrambleType));
  });

  it("exports csv", () => {
    const csv = exportCsv([{ id: "a", scrambleType: "333", time: 10000, penalty: 2000, scramble: 'R "U"', date: 0 }]);
    expect(csv.split("\n")[1]).toBe('1,10000,+2,12000,"R ""U""",1970-01-01T00:00:00.000Z');
  });
});

describe("v1 migration", () => {
  it("converts every solve into its puzzle profile", () => {
    const m = migrateV1({
      schemaVersion: 1,
      sessions: [{ id: "s1", name: "333 Session", puzzleId: "333", createdAt: "2024-01-01T00:00:00Z" }],
      solves: [
        {
          id: "a",
          sessionId: "s1",
          puzzleId: "333",
          scramble: { puzzleId: "333", notation: "R U" },
          timing: { rawDurationMs: 12000.4, inspectionDurationMs: 8000, penalty: "+2", finalDurationMs: 14000 },
          createdAt: "2024-01-01T00:01:00Z",
        },
        {
          id: "b",
          sessionId: "gone",
          puzzleId: "222",
          scramble: { puzzleId: "222", notation: "F" },
          timing: { rawDurationMs: 5000, inspectionDurationMs: 0, penalty: "dnf", finalDurationMs: null },
          createdAt: "2024-01-01T00:02:00Z",
        },
      ],
      splits: [{ solveId: "a", phases: [{ phase: "Cross", timestampMs: 0 }, { phase: "F2L", timestampMs: 3000 }, { phase: "LL", timestampMs: 9000 }] }],
      settings: { inspectionEnabled: true, showMilliseconds: true },
      activePuzzleId: "333",
    });
    expect(m.solves.map((s) => [s.id, s.scrambleType, s.time, s.penalty])).toEqual([
      ["a", "333", 12000, 2000],
      ["b", "222", 5000, -1],
    ]);
    expect(m.solves[0]!.splits).toEqual([3000, 9000]);
    expect(m.settings.inspection).toBe(true);
    expect(m.settings.showMs).toBe(true);
    expect(m.profile).toBe("333");
  });
});
